from __future__ import annotations
import json
from models import db, Category, Question, DailyPlan

CATEGORIES = [
    {'code': 'exam_senior', 'name': '高中健護甄試題庫', 'description': '近10年高中健康與護理教師甄試筆試題', 'sort_order': 1},
    {'code': 'exam_junior', 'name': '國中健教甄試題庫', 'description': '近10年國中健康教育教師甄試題', 'sort_order': 2},
    {'code': 'technician',  'name': '四技二專健護題庫', 'description': '四技二專統測健護相關考題', 'sort_order': 3},
    {'code': 'curriculum108', 'name': '108課綱新興題', 'description': '108課綱素養導向、SDGs、雙語教學等新興考題', 'sort_order': 4},
]

DAILY_PLANS = [
    # 第1週：生理學與護理基礎
    (1,  '循環系統與心臟急救', '心臟解剖,CPR,AED,心血管疾病', 20, False, 'exam_senior,exam_junior'),
    (2,  '呼吸系統與氣道處理', '呼吸解剖,氣道阻塞,人工呼吸,哮喘', 20, False, 'exam_senior,exam_junior'),
    (3,  '神經系統與意識評估', '神經系統,意識狀態,腦中風,AVPU', 20, False, 'exam_senior,technician'),
    (4,  '急救原則與止血包紮', '急救原則,止血方法,包紮技術,骨折固定', 20, False, 'exam_senior,exam_junior'),
    (5,  '傳染病防治與流行病學', '傳染病分類,隔離措施,疫苗接種,三段五級', 20, False, 'exam_senior,technician'),
    (6,  '護理技術與醫療安全', '護理評估,給藥安全,感染控制,醫療倫理', 20, False, 'exam_senior'),
    (7,  '第1週錯題複習', '循環,呼吸,神經,急救,傳染病,護理', 15, True,  'exam_senior,exam_junior,technician'),
    # 第2週：健康教育學科知識
    (8,  '生長發育與青少年健康', '青春期,生理發育,心理發展,性教育', 20, False, 'exam_senior,curriculum108'),
    (9,  '慢性病預防與自我管理', '糖尿病,高血壓,癌症篩檢,健康促進', 20, False, 'exam_senior,technician'),
    (10, '心理健康與壓力調適', '心理健康定義,焦慮憂鬱,自殺防治,正向心理', 20, False, 'exam_senior,curriculum108'),
    (11, '性別平等與多元健康', '性別平等,LGBTQ,家庭暴力,性騷擾', 20, False, 'exam_senior,curriculum108'),
    (12, '藥物濫用與成癮防治', '毒品分級,成癮機制,防治策略,酒精菸草', 20, False, 'exam_senior,technician'),
    (13, '環境衛生與職業健康', '環境污染,職業病,食品安全,飲用水', 20, False, 'exam_senior,technician'),
    (14, '第2週錯題複習', '生長發育,慢性病,心理健康,性別,藥物,環境', 15, True,  'exam_senior,curriculum108'),
    # 第3週：108課綱教學法
    (15, '108課綱核心素養', '核心素養三面九項,素養導向教學,學習遷移', 20, False, 'curriculum108'),
    (16, '素養導向教學設計', 'UbD逆向設計,真實評量,PBL專題學習', 20, False, 'curriculum108'),
    (17, 'ICT科技輔助教學', '數位學習,教育科技,Kahoot,Padlet,AI教育', 20, False, 'curriculum108'),
    (18, '雙語教學CLIL策略', 'CLIL四C,雙語環境,英語授課,學科語言', 20, False, 'curriculum108'),
    (19, '差異化教學與特殊教育', '差異化策略,IEP,融合教育,多元智能', 20, False, 'curriculum108'),
    (20, '健康促進學校與社區', '健康促進學校,WHO渥太華憲章,社區衛生', 20, False, 'exam_senior,curriculum108'),
    (21, '第3週錯題複習', '108課綱,素養,ICT,雙語,差異化,健促', 15, True,  'curriculum108'),
    # 第4週：模擬衝刺
    (22, '四技二專統測模擬（一）', '四技二專,護理基礎,解剖生理', 25, False, 'technician'),
    (23, '四技二專統測模擬（二）', '四技二專,健康促進,急救技能', 25, False, 'technician'),
    (24, '歷屆高中甄試模擬（一）', '甄試筆試,生理護理,教育理論', 25, False, 'exam_senior'),
    (25, '歷屆高中甄試模擬（二）', '甄試筆試,慢性病,心理健康,108課綱', 25, False, 'exam_senior,curriculum108'),
    (26, '口試模擬練習（教學演示）', '教學設計,口試技巧,教案撰寫,板書規劃', 15, False, 'curriculum108'),
    (27, '口試模擬練習（情境問答）', '班級經營,突發狀況,護理倫理,溝通技巧', 15, False, 'exam_senior'),
    (28, '弱點科目強化', '個人弱點標籤', 25, False, 'exam_senior,curriculum108'),
    (29, '全科錯題總複習', '所有錯題,間隔複習,重點整理', 30, True,  'exam_senior,exam_junior,technician,curriculum108'),
    (30, '考前最後衝刺', '重點回顧,心態調整,模擬考試', 20, False, 'exam_senior,curriculum108'),
]

SAMPLE_QUESTIONS = [
    {
        'category_code': 'exam_senior',
        'q_type': 'single',
        'year': 2023,
        'source': '112年高中健護甄試',
        'stem': '依據三段五級預防醫學概念，下列何者屬於「第二段預防」的措施？',
        'options': [
            {'key': 'A', 'text': '推廣均衡飲食、規律運動'},
            {'key': 'B', 'text': '定期健康檢查以早期發現疾病'},
            {'key': 'C', 'text': '手術切除腫瘤'},
            {'key': 'D', 'text': '復健治療以恢復功能'},
        ],
        'answer': 'B',
        'explanation': '三段五級中，第二段預防包含第三級（早期診斷）和第四級（適切治療），目的是早期發現、早期治療。A為第一段第一級（促進健康）；C為第二段第四級（適切治療）；D為第三段第五級（復健）。',
        'difficulty': 2,
        'tags': '三段五級,預防醫學',
    },
    {
        'category_code': 'exam_senior',
        'q_type': 'single',
        'year': 2022,
        'source': '111年高中健護甄試',
        'stem': '執行成人心肺復甦術（CPR）時，胸外按壓的正確頻率與深度為何？',
        'options': [
            {'key': 'A', 'text': '頻率60-80次/分，深度2公分'},
            {'key': 'B', 'text': '頻率100-120次/分，深度至少5公分'},
            {'key': 'C', 'text': '頻率80-100次/分，深度3-4公分'},
            {'key': 'D', 'text': '頻率120-140次/分，深度至少6公分'},
        ],
        'answer': 'B',
        'explanation': '依據2020年AHA心肺復甦術指引，成人胸外按壓頻率為100-120次/分，深度至少5公分（但不超過6公分），按壓後須讓胸廓完全回彈。',
        'difficulty': 1,
        'tags': 'CPR,急救,AHA',
    },
    {
        'category_code': 'exam_senior',
        'q_type': 'multiple',
        'year': 2023,
        'source': '112年高中健護甄試',
        'stem': '下列關於青少年心理健康的敘述，哪些是正確的？（複選）',
        'options': [
            {'key': 'A', 'text': '青少年憂鬱症的盛行率高於成人'},
            {'key': 'B', 'text': '自我傷害行為不一定代表有自殺意念'},
            {'key': 'C', 'text': '社群媒體使用與青少年心理健康無關'},
            {'key': 'D', 'text': '朋友的支持是青少年心理健康的保護因子'},
            {'key': 'E', 'text': '學業壓力是青少年焦慮的常見原因之一'},
        ],
        'answer': 'B,D,E',
        'explanation': 'B正確：自我傷害（如割腕）可能是情緒調節方式，不一定有自殺意念。D正確：同儕支持是重要保護因子。E正確：學業壓力是青少年焦慮主因之一。A錯誤：青少年憂鬱症盛行率約4-8%，低於成人的10-20%。C錯誤：大量研究顯示過度使用社群媒體與青少年憂鬱、焦慮有關聯。',
        'difficulty': 3,
        'tags': '心理健康,青少年,憂鬱症',
    },
    {
        'category_code': 'curriculum108',
        'q_type': 'single',
        'year': 2023,
        'source': '112年108課綱相關考題',
        'stem': '108課綱強調「素養導向教學」，下列何者最能體現素養導向的教學設計原則？',
        'options': [
            {'key': 'A', 'text': '以教師講述為主，重視知識傳遞的完整性'},
            {'key': 'B', 'text': '設計真實情境任務，讓學生在情境中整合知識、技能與態度'},
            {'key': 'C', 'text': '增加記憶性題目的比重，確保學科知識紮實'},
            {'key': 'D', 'text': '以統一的教材和評量，確保學習目標一致'},
        ],
        'answer': 'B',
        'explanation': '素養導向教學的核心在於「真實情境」與「整合運用」，強調學生能在真實或模擬情境中，統整知識、技能與態度來解決問題，而非單純記憶知識。',
        'difficulty': 2,
        'tags': '108課綱,素養導向,教學設計',
    },
    {
        'category_code': 'curriculum108',
        'q_type': 'essay',
        'year': 2024,
        'source': '113年教師甄試口試模擬',
        'stem': '請說明您如何在健康與護理課程中融入「性別平等教育」，並舉出至少兩個具體教學活動設計。',
        'options': [],
        'answer': 'essay',
        'key_points': [
            '說明性別平等教育的核心理念（尊重多元、消除偏見）',
            '結合健護課程主題（如生殖健康、家暴防治）',
            '教學活動一：案例討論（真實新聞情境分析）',
            '教學活動二：角色扮演或辯論（不同性別角色體驗）',
            '評量方式設計（過程評量、反思日誌）',
            '補充：與其他議題課程連結（人權、多元文化）',
        ],
        'explanation': '性別平等教育是108課綱重要議題之一，需融入健護課的性教育、家庭健康等單元，強調批判思考與生活應用。',
        'difficulty': 3,
        'tags': '性別平等,口試,教學設計,議題融入',
    },
    {
        'category_code': 'technician',
        'q_type': 'single',
        'year': 2022,
        'source': '111年四技二專統測',
        'stem': '護理師在執行靜脈注射時，下列哪一步驟的順序是正確的？',
        'options': [
            {'key': 'A', 'text': '消毒皮膚→戴手套→進針→固定針頭'},
            {'key': 'B', 'text': '戴手套→消毒皮膚→進針→固定針頭'},
            {'key': 'C', 'text': '進針→消毒皮膚→固定針頭→戴手套'},
            {'key': 'D', 'text': '戴手套→進針→消毒皮膚→固定針頭'},
        ],
        'answer': 'B',
        'explanation': '靜脈注射正確步驟：手部衛生→戴手套→選擇血管→消毒皮膚（由中心向外圓周運動）→待乾→進針→確認回血→固定針頭→調整滴速。',
        'difficulty': 2,
        'tags': '護理技術,靜脈注射,感染控制',
    },
    {
        'category_code': 'exam_senior',
        'q_type': 'single',
        'year': 2021,
        'source': '110年高中健護甄試',
        'stem': '世界衛生組織（WHO）在1986年「渥太華健康促進憲章」中，提出健康促進的五大行動策略，下列何者不包含在內？',
        'options': [
            {'key': 'A', 'text': '建立健康的公共政策'},
            {'key': 'B', 'text': '強化社區行動'},
            {'key': 'C', 'text': '發展個人技能'},
            {'key': 'D', 'text': '推廣醫療化治療'},
        ],
        'answer': 'D',
        'explanation': '渥太華憲章五大行動策略：1.建立健康的公共政策、2.創造健康支持環境、3.強化社區行動、4.發展個人技能、5.調整衛生服務方向。「推廣醫療化治療」不在其中，WHO強調的是健康促進而非醫療化。',
        'difficulty': 2,
        'tags': '健康促進,渥太華憲章,WHO',
    },
    {
        'category_code': 'curriculum108',
        'q_type': 'essay',
        'year': 2024,
        'source': '113年教師甄試口試模擬',
        'stem': '請說明CLIL（內容與語言整合學習）在健護雙語課程中的應用策略，並說明如何評估學生的學習成效。',
        'options': [],
        'answer': 'essay',
        'key_points': [
            '說明CLIL四C框架：內容(Content)、認知(Cognition)、溝通(Communication)、文化(Culture)',
            '健護課CLIL具體應用：選定適合雙語教學的主題（如急救、慢性病預防）',
            '教學策略：關鍵字彙表、圖解輔助、漸進式語言鷹架',
            '課室活動設計：英語情境對話、英文案例閱讀',
            '評量策略：過程評量、作品評量、語言與內容分別評分',
            '挑戰與因應：程度分組、混語使用策略',
        ],
        'explanation': '雙語教學是108課綱重要政策，CLIL強調語言學習融入學科內容，教師需兼顧健護學科知識與英語溝通能力的培養。',
        'difficulty': 3,
        'tags': 'CLIL,雙語教學,108課綱,口試',
    },
    {
        'category_code': 'exam_junior',
        'q_type': 'single',
        'year': 2022,
        'source': '111年國中健教甄試',
        'stem': '青少年飲食障礙症中，「神經性厭食症」最常見的特徵是什麼？',
        'options': [
            {'key': 'A', 'text': '強迫性暴食後自行催吐'},
            {'key': 'B', 'text': '對體重增加有強烈恐懼，嚴格限制飲食'},
            {'key': 'C', 'text': '對食物種類有強迫性的偏好'},
            {'key': 'D', 'text': '僅在壓力時才出現進食問題'},
        ],
        'answer': 'B',
        'explanation': '神經性厭食症（Anorexia Nervosa）特徵：對體重增加有強烈恐懼、嚴格限制食物攝取、體重過輕、體像扭曲。A描述的是神經性暴食症（Bulimia Nervosa）的特徵。',
        'difficulty': 2,
        'tags': '飲食障礙,青少年,心理健康',
    },
    {
        'category_code': 'exam_senior',
        'q_type': 'single',
        'year': 2020,
        'source': '109年高中健護甄試',
        'stem': '依據《學校衛生法》，學校應設置哪些健康相關設施或人員？（關於「護理師配置」的規定）',
        'options': [
            {'key': 'A', 'text': '24班以上學校需設置1名護理師'},
            {'key': 'B', 'text': '40班以上學校需設置2名護理師'},
            {'key': 'C', 'text': '所有學校均需設置至少1名護理師'},
            {'key': 'D', 'text': '護理師配置由各縣市政府自行決定'},
        ],
        'answer': 'A',
        'explanation': '依《學校衛生法》第7條，國中以上學校每24班應置護理師1人。高中健護教師需熟悉相關法規，此為甄試常考法規題。',
        'difficulty': 3,
        'tags': '學校衛生法,護理師配置,法規',
    },
    # ── 2025年時事新知題目 ──────────────────────────────────────
    {
        'category_code': 'exam_senior',
        'q_type': 'single',
        'year': 2025,
        'source': '2025年時事新知',
        'stem': '2025年WHO世界衛生日（4月7日）的主題為何？',
        'options': [
            {'key': 'A', 'text': 'My Health, My Right（我的健康，我的權利）'},
            {'key': 'B', 'text': 'Health for All（人人享有健康）'},
            {'key': 'C', 'text': 'Healthy Beginnings, Hopeful Futures（健康起點，希望未來）'},
            {'key': 'D', 'text': 'Our Planet, Our Health（我們的地球，我們的健康）'},
        ],
        'answer': 'C',
        'explanation': '2025年WHO世界衛生日主題為「Healthy Beginnings, Hopeful Futures（健康起點，希望未來）」，聚焦孕產婦與新生兒照護。歷年主題：2024年「My Health, My Right（我的健康，我的權利）」、2023年「Health for All（人人享有健康）」、2022年「Our Planet, Our Health（我們的地球，我們的健康）」。',
        'difficulty': 2,
        'tags': 'WHO,世界衛生日,健康促進,時事',
    },
    {
        'category_code': 'exam_senior',
        'q_type': 'single',
        'year': 2025,
        'source': '2025年時事新知',
        'stem': '台灣在2025年正式跨入超高齡社會（Super-aged Society），其判斷標準為老年人口（65歲以上）占總人口比例達到多少？',
        'options': [
            {'key': 'A', 'text': '7%以上'},
            {'key': 'B', 'text': '14%以上'},
            {'key': 'C', 'text': '20%以上'},
            {'key': 'D', 'text': '25%以上'},
        ],
        'answer': 'C',
        'explanation': '依WHO定義：7%=高齡化社會、14%=高齡社會、20%=超高齡社會。台灣2018年進入高齡社會，2025年老年人口突破20%，正式成為超高齡社會。從高齡社會到超高齡社會僅約7年（法國155年、日本10年），速度居全球前列。',
        'difficulty': 2,
        'tags': '高齡化,超高齡社會,長照,人口結構',
    },
    {
        'category_code': 'exam_senior',
        'q_type': 'single',
        'year': 2024,
        'source': '2024年食安事件',
        'stem': '2024年3月台北「寶林茶室」食物中毒事件，為台灣首見的何種毒素中毒案例？',
        'options': [
            {'key': 'A', 'text': '肉毒桿菌毒素（Botulinum toxin）'},
            {'key': 'B', 'text': '邦克列酸（Bongkrekic Acid）'},
            {'key': 'C', 'text': '蘇丹紅（Sudan Red）'},
            {'key': 'D', 'text': '黃麴毒素（Aflatoxin）'},
        ],
        'answer': 'B',
        'explanation': '2024年3月寶林茶室事件為台灣首例邦克列酸（Bongkrekic Acid）中毒，造成33人受害、6人死亡。邦克列酸由發酵穀物假單胞菌在缺氧環境下產生，常見於腐壞的發酵食品（粿條、河粉等）。此毒素耐熱，一般烹調無法破壞，主要抑制細胞粒線體功能導致器官衰竭。',
        'difficulty': 3,
        'tags': '食安,邦克列酸,食物中毒,傳染病防治',
    },
    {
        'category_code': 'exam_senior',
        'q_type': 'single',
        'year': 2024,
        'source': '2024年食安事件',
        'stem': '2024年2月台灣爆發辣椒粉含有蘇丹紅（Sudan Red）事件，蘇丹紅屬於哪一類有害物質？',
        'options': [
            {'key': 'A', 'text': '重金屬污染物'},
            {'key': 'B', 'text': '農藥殘留物'},
            {'key': 'C', 'text': '工業用染料（致癌物）'},
            {'key': 'D', 'text': '天然毒素'},
        ],
        'answer': 'C',
        'explanation': '蘇丹紅是工業用偶氮染料，屬IARC第3類可能致癌物。台灣2024年事件中，蘇丹紅3號被非法添加於食品用辣椒粉，含量達18ppb以上。依食品安全衛生管理法，蘇丹紅不得用於食品，違者可處7年以下有期徒刑。',
        'difficulty': 2,
        'tags': '食安,蘇丹紅,食品添加物,致癌物',
    },
    {
        'category_code': 'curriculum108',
        'q_type': 'single',
        'year': 2024,
        'source': '108課綱健康識能',
        'stem': '健康識能（Health Literacy）的三個層次，由低至高排列正確的是？',
        'options': [
            {'key': 'A', 'text': '互動性識能→功能性識能→批判性識能'},
            {'key': 'B', 'text': '功能性識能→互動性識能→批判性識能'},
            {'key': 'C', 'text': '批判性識能→互動性識能→功能性識能'},
            {'key': 'D', 'text': '功能性識能→批判性識能→互動性識能'},
        ],
        'answer': 'B',
        'explanation': 'Nutbeam（2000）提出健康識能三層次（由低至高）：①功能性識能（Functional）：能讀寫基本健康資訊；②互動性識能（Interactive）：能與醫療人員溝通互動；③批判性識能（Critical）：能評估健康資訊、影響社會政策。台灣2017年調查顯示成人健康識能不足者達51.6%。',
        'difficulty': 2,
        'tags': '健康識能,Health Literacy,108課綱,Nutbeam',
    },
    {
        'category_code': 'curriculum108',
        'q_type': 'single',
        'year': 2025,
        'source': '108課綱新興議題',
        'stem': '「超加工食品」（Ultra-Processed Food, UPF）的分類依據NOVA系統，屬於第幾類食品？',
        'options': [
            {'key': 'A', 'text': '第一類（未加工或最低限度加工食品）'},
            {'key': 'B', 'text': '第二類（廚房用加工食材）'},
            {'key': 'C', 'text': '第三類（加工食品）'},
            {'key': 'D', 'text': '第四類（超加工食品）'},
        ],
        'answer': 'D',
        'explanation': 'NOVA食品分類系統（Monteiro, 2010）：第1類=未加工食品（蔬果、肉類）；第2類=廚房食材（油、鹽）；第3類=加工食品（罐頭、醃製品）；第4類=超加工食品（含多種添加物的工業製品）。2025年美國DGA首度正式警示超加工食品，研究顯示與多種慢性病及死亡率呈劑量反應關係。',
        'difficulty': 3,
        'tags': '超加工食品,NOVA,食品安全,飲食指南',
    },
    {
        'category_code': 'exam_senior',
        'q_type': 'single',
        'year': 2025,
        'source': '青少年健康新知',
        'stem': '根據2025年兒福聯盟調查，台灣青少年有心理困擾時，最常尋求哪種管道協助（比例甚至高於輔導室）？',
        'options': [
            {'key': 'A', 'text': '家長'},
            {'key': 'B', 'text': '同儕朋友'},
            {'key': 'C', 'text': '生成式AI（如ChatGPT）'},
            {'key': 'D', 'text': '心理諮商師'},
        ],
        'answer': 'C',
        'explanation': '2025年兒福聯盟調查，台灣青少年有心理困擾時，46.5%曾向生成式AI求助，高於輔導室（41.1%）。這反映AI工具在青少年心理支持中的新角色，教師需教導青少年辨別AI諮詢的限制，同時鼓勵正式求助管道。',
        'difficulty': 3,
        'tags': '青少年心理健康,AI,生成式AI,輔導',
    },
    {
        'category_code': 'exam_senior',
        'q_type': 'single',
        'year': 2025,
        'source': '青少年健康新知',
        'stem': 'WHO的ICD-11（2022年生效）正式將哪項列為診斷疾病？',
        'options': [
            {'key': 'A', 'text': '網路購物成癮（Compulsive Buying Disorder）'},
            {'key': 'B', 'text': '遊戲疾患（Gaming Disorder）'},
            {'key': 'C', 'text': '手機依賴症（Smartphone Addiction）'},
            {'key': 'D', 'text': '社群媒體成癮（Social Media Addiction）'},
        ],
        'answer': 'B',
        'explanation': 'WHO的ICD-11（2022年生效）首度將「遊戲疾患（Gaming Disorder）」列為正式診斷疾病，診斷標準包含：控制能力受損、遊戲優先於其他活動、症狀持續12個月以上。DSM-5將其列為「需進一步研究的狀況」（尚未正式納入診斷）。台灣約3.1%青少年有網路遊戲沉迷問題。',
        'difficulty': 2,
        'tags': '遊戲疾患,ICD-11,網路成癮,青少年健康',
    },
    {
        'category_code': 'exam_senior',
        'q_type': 'single',
        'year': 2025,
        'source': '長照新制',
        'stem': '台灣長照3.0計畫（2026年起實施）的三大核心願景不包含下列何者？',
        'options': [
            {'key': 'A', 'text': '健康老化'},
            {'key': 'B', 'text': '在地安老'},
            {'key': 'C', 'text': '安寧善終'},
            {'key': 'D', 'text': '機構安養'},
        ],
        'answer': 'D',
        'explanation': '長照3.0三大核心願景：①健康老化、②在地安老（在熟悉社區老化）、③安寧善終。長照政策強調「去機構化」，優先支持居家和社區式照護。長照2.0（2017年起）長照ABC據點已達15,051處，長照3.0進一步整合醫療與照顧的連續服務。',
        'difficulty': 2,
        'tags': '長照3.0,高齡化,長期照護,在地安老',
    },
    {
        'category_code': 'exam_senior',
        'q_type': 'single',
        'year': 2025,
        'source': '傳染病防治新知',
        'stem': '登革熱防治口訣「巡、倒、清、刷」中，「刷」指的是什麼？',
        'options': [
            {'key': 'A', 'text': '刷牙保持口腔衛生，避免病菌感染'},
            {'key': 'B', 'text': '刷洗積水容器內壁，清除蚊卵'},
            {'key': 'C', 'text': '用刷子清掃落葉，減少蚊蟲棲息地'},
            {'key': 'D', 'text': '用毛刷塗抹防蚊液於皮膚上'},
        ],
        'answer': 'B',
        'explanation': '登革熱防治「巡倒清刷」：①巡：巡視積水容器；②倒：倒除積水；③清：清除不需要的容器；④刷：刷洗容器內壁清除蚊卵（蚊卵附著力強，僅倒水不足）。台灣2024年登革熱境外移入155例，創8年同期新高。',
        'difficulty': 1,
        'tags': '登革熱,傳染病,防治,斑蚊',
    },
    {
        'category_code': 'curriculum108',
        'q_type': 'single',
        'year': 2025,
        'source': '精準健康新知',
        'stem': '「精準健康（Precision Health）」相較於傳統醫療，最大的進步是將重心從何處轉移？',
        'options': [
            {'key': 'A', 'text': '從西方醫學轉移至傳統中醫'},
            {'key': 'B', 'text': '從治療疾病轉移至預測、預防與個人化健康管理'},
            {'key': 'C', 'text': '從公共衛生轉移至個人責任'},
            {'key': 'D', 'text': '從醫院診療轉移至居家護理'},
        ],
        'answer': 'B',
        'explanation': '精準健康以「預測→預防→診斷→治療→照護」連續模式取代傳統「生病才就醫」模式。台灣行政院以2030年為目標建構「全齡精準健康」生態系，中研院主導TPMI台灣精準醫療計畫，結合16家醫療體系建立亞洲最大漢人生醫大數據庫。',
        'difficulty': 2,
        'tags': '精準健康,AI醫療,預防醫學,新興議題',
    },
    {
        'category_code': 'exam_senior',
        'q_type': 'single',
        'year': 2025,
        'source': '心理健康新知',
        'stem': '台灣「全民心理健康韌性計畫（2025-2030）」的三大核心策略不包含下列何者？',
        'options': [
            {'key': 'A', 'text': '預防（Prevention）'},
            {'key': 'B', 'text': '去污名（De-stigmatization）'},
            {'key': 'C', 'text': '識能（Literacy）'},
            {'key': 'D', 'text': '強制就醫（Compulsory Treatment）'},
        ],
        'answer': 'D',
        'explanation': '國健署「全民心理健康韌性計畫（2025-2030）」三大策略：①預防、②識能（提升心理健康識能）、③去污名（減少對心理疾病的偏見）。此計畫強調自願性促進，而非強制性措施。',
        'difficulty': 2,
        'tags': '心理健康,去污名,韌性,衛福部',
    },
    {
        'category_code': 'exam_senior',
        'q_type': 'single',
        'year': 2024,
        'source': '青少年睡眠健康',
        'stem': '美國國家睡眠基金會（NSF）建議青少年（14-17歲）每天的睡眠時數為何？',
        'options': [
            {'key': 'A', 'text': '6-8小時'},
            {'key': 'B', 'text': '7-9小時'},
            {'key': 'C', 'text': '8-10小時'},
            {'key': 'D', 'text': '9-11小時'},
        ],
        'answer': 'C',
        'explanation': 'NSF建議：學齡兒童（6-13歲）9-11小時、青少年（14-17歲）8-10小時、成人（18-64歲）7-9小時、長者（65歲以上）7-8小時。台灣調查顯示青少年平日睡眠不足比率達58.3%，近47.9%有慢性睡眠不足問題。',
        'difficulty': 2,
        'tags': '睡眠健康,青少年,NSF,生理時鐘',
    },
    {
        'category_code': 'exam_senior',
        'q_type': 'multiple',
        'year': 2025,
        'source': '食品標示法規',
        'stem': '依台灣現行「食品安全衛生管理法」規定，下列哪些是包裝食品「必須」標示的內容？（複選）',
        'options': [
            {'key': 'A', 'text': '品名與內容物'},
            {'key': 'B', 'text': '有效日期'},
            {'key': 'C', 'text': '製造商名稱、電話及地址'},
            {'key': 'D', 'text': '產品得獎記錄'},
            {'key': 'E', 'text': '營養標示'},
        ],
        'answer': 'A,B,C,E',
        'explanation': '依食安法第22條，包裝食品必須標示：品名、內容物、添加物、製造廠商資訊、有效日期、營養標示、GMO說明等。「產品得獎記錄」為自願性標示，非強制要求。2025年起嬰兒食品不得標示「優於母乳」等誇大字樣。',
        'difficulty': 3,
        'tags': '食品標示,食安法,食品安全,法規',
    },
    {
        'category_code': 'exam_senior',
        'q_type': 'single',
        'year': 2025,
        'source': '校園霸凌防治',
        'stem': '依台灣「教育部校園霸凌防制準則」，霸凌行為的四大要素不包含下列何者？',
        'options': [
            {'key': 'A', 'text': '重複性（反覆發生）'},
            {'key': 'B', 'text': '傷害性（對被霸凌者造成身心傷害）'},
            {'key': 'C', 'text': '偶發性（偶爾發生一次）'},
            {'key': 'D', 'text': '力量不平衡（欺凌者具有優勢）'},
        ],
        'answer': 'C',
        'explanation': '霸凌四大要素：①重複性（非偶發）、②傷害性、③故意性、④力量不平衡。「偶發性」是霸凌的反面特徵，單次衝突通常不構成霸凌。2024年兒福聯盟調查顯示台灣遭霸凌比率10.2%，言語霸凌（64.9%）最常見。',
        'difficulty': 2,
        'tags': '校園霸凌,防制準則,青少年健康,輔導',
    },
]


def seed_all(app, db_instance):
    with app.app_context():
        # Seed categories
        for cat_data in CATEGORIES:
            existing = Category.query.filter_by(code=cat_data['code']).first()
            if not existing:
                cat = Category(**cat_data)
                db_instance.session.add(cat)
        db_instance.session.commit()

        # Seed questions (only if empty)
        if Question.query.count() == 0:
            for q_data in SAMPLE_QUESTIONS:
                cat = Category.query.filter_by(code=q_data['category_code']).first()
                if not cat:
                    continue
                key_points = q_data.pop('key_points', [])
                options = q_data.pop('options', [])
                category_code = q_data.pop('category_code')
                q = Question(
                    category_id=cat.id,
                    q_type=q_data['q_type'],
                    year=q_data.get('year'),
                    source=q_data.get('source', ''),
                    stem=q_data['stem'],
                    options_json=json.dumps(options, ensure_ascii=False),
                    answer=q_data['answer'],
                    key_points_json=json.dumps(key_points, ensure_ascii=False),
                    explanation=q_data.get('explanation', ''),
                    difficulty=q_data.get('difficulty', 2),
                    tags=q_data.get('tags', ''),
                )
                db_instance.session.add(q)
            db_instance.session.commit()

        # Seed daily plans
        for (day_num, title, key_points, target_q, is_review, cat_codes) in DAILY_PLANS:
            existing = DailyPlan.query.filter_by(day_number=day_num).first()
            if not existing:
                plan = DailyPlan(
                    day_number=day_num,
                    title=title,
                    key_points=key_points,
                    target_questions=target_q,
                    is_review_day=is_review,
                    category_codes=cat_codes,
                )
                db_instance.session.add(plan)
        db_instance.session.commit()
